### ISSUE TITLE
Entire game crashes when I chop a tree

### ISSUE THREAD

**Issue by snxpdrxgun** [hammertater/treechop#236]
When i chop the first log my game keeps crashing, i tried to check i have all of the correct files installed (1.20.1 fabric of HT's TreeChop and 1.20.2 forge confic api port)
but every time i've tried to use the mod it's crashed my game completely

exit code:
The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'net.minecraft.class_2540 net.minecraft.class_2540.method_10794(net.minecraft.class_2487)' 
-1

crash report:
[crash-2023-10-26_20.53.26-server.txt](https://github.com/hammertater/treechop/files/13184275/crash-2023-10-26_20.53.26-server.txt)

thank you in advance for any help!

**Comment by snxpdrxgun** [comment]
oh, in case it matters, these are the other mods i have!
![image](https://github.com/hammertater/treechop/assets/149127850/479e1bb3-6655-463c-b725-ba1b12ab9fd7)

**Comment by hammertater** [comment]
Ahh, looks like TreeChop doesn't work on 1.20.2. I'll get it fixed!

**Comment by const703** [comment]
> Ahh, looks like TreeChop doesn't work on 1.20.2. I'll get it fixed!

@hammertater Hey man, is there any update on that? I feel like I've been using your mod forever, it's the best tree chopping mod out there

**Comment by hammertater** [comment]
Hey @const703, for sure - it's in the works, hopefully it'll be out by next weekend!
